package mastermind_save_load;
import java.io.*;

/**
 * Save MasterMind to file
 */
public class save {
  File filename;

  /**
   * Class construction
   *
   * @param filen absolute path to the file
   */
  public save (File filen) {
    filename = filen;
  }

  /**
   * Saves exported important core objects to file
   *
   * @param mastermind_game object generated by core
   * @see mastermind_core.core#makePKG()
   */
  public void savefile(Object mastermind_game) throws IOException {
    try {
      FileOutputStream saveFile = new FileOutputStream(filename);
      ObjectOutputStream save = new ObjectOutputStream(saveFile);
      save.writeObject(mastermind_game);
      save.close();
    } catch(Exception exc){
     throw exc;//Redirect Error to GUI
    }
  }
}
